name: supporter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  fixture_repository:
    path: packages/fixture_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations: 
    sdk: flutter
  football_api:
    path: packages/football_api
  http: ^0.13.5
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  mockingjay: ^0.3.0
  path_provider: ^2.0.11
  team_repository:
    path: packages/team_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
